spring:
  cloud:
    gateway:
      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/auth/register , /api/v1/users/auth/login
          filters:
            - StripPrefix=2
        - id: user-service-private
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: tweets-service
          uri: lb://TWEET-SERVICE
          predicates:
            - Path=/api/v1/tweets/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: follow-service
          uri: lb://FOLLOW-SERVICE
          predicates:
            - Path=/api/v1/follows/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/api/v1/messages/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

