spring.application.name: uploader-service

server.servlet.context-path: /uploads
server.port: 8010
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
eureka.instance.preferIpAddress: true

cloudinary:
  cloud-name: { CLOUDINARY-CLOUD-NAME }
  api-key: { CLOUDINARY-API-KEY }
  api-secret: { CLOUDINARY-API-SECRET }

